### ISSUE TITLE
Doesnt run under python 3.10

### ISSUE THREAD

**Issue by hcjehg** [keton/etrv2mqtt#17]
Python 3.10 gives:

(etrv2mqtt) [root@HomeAssistant etrv2mqtt]# ~/venv/etrv2mqtt/bin/python3 -m libetrv.cli scan
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/venv/etrv2mqtt/lib/python3.10/site-packages/libetrv/cli.py", line 3, in <module>
    from libetrv.device import eTRVDevice
  File "/root/venv/etrv2mqtt/lib/python3.10/site-packages/libetrv/device.py", line 8, in <module>
    from .data_struct import BatteryData, SettingsData, TemperatureData, CurrentTimeData, SecretKeyData, NameData
  File "/root/venv/etrv2mqtt/lib/python3.10/site-packages/libetrv/data_struct.py", line 3, in <module>
    from .properties import eTRVData, eTRVSingleData
  File "/root/venv/etrv2mqtt/lib/python3.10/site-packages/libetrv/properties.py", line 5, in <module>
    from .utils import etrv_read_data, etrv_write_data
  File "/root/venv/etrv2mqtt/lib/python3.10/site-packages/libetrv/utils.py", line 1, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

**Comment by anx-cbenke** [comment]
Workaround: In `etrv2mqtt/lib/python3.10/site-packages/libetrv/utils.py` replace the first line

`from collections import Iterable` with

`from collections.abc import Iterable`

**Comment by keton** [comment]
this needs to be fixed in libetrv not here.
